/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright (C) 2026 The Platypus Authors */
/* Platypus FFI — C ABI over platypus-core.
 *
 * GENERATED by cbindgen from crates/platypus-ffi/src/lib.rs — do NOT edit by hand.
 * Regenerate with `just gen-header`.
 *
 * Memory: every char* returned by a *_json function is owned by Rust; release it with
 * platypus_string_free. Every opaque handle (PlatypusHpdb*, PlatypusLibrary*, …) has a
 * matching *_free/_close. All functions tolerate null arguments. */

#ifndef PLATYPUS_H
#define PLATYPUS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque handle: a built favorites document, ready to preview and commit.
 */
typedef struct PlatypusFavorites PlatypusFavorites;

/*
 Opaque handle: a decoded FT-60 clone image.
 */
typedef struct PlatypusFt60 PlatypusFt60;

/*
 Opaque handle: a parsed HPDB document plus the profile to interpret it.
 */
typedef struct PlatypusHpdb PlatypusHpdb;

/*
 Opaque handle: the whole loaded HPDB library — every `s_*.hpd` in a directory,
 parsed and held in memory. Filtering runs over this (microseconds, benchmarked),
 so no database is needed for browse speed.
 */
typedef struct PlatypusLibrary PlatypusLibrary;

/*
 An open RadioReference browse session: the client + the resolved location + the county system
 list, plus a lazy cache of fully-fetched systems (keyed by the ref used as each row's JSON `id`:
 `"t<sid>"` for a trunked system, `"c<scid>"` for a conventional subcategory).
 */
typedef struct PlatypusRrSource PlatypusRrSource;

/*
 A C progress callback: `(ctx, phase, done, total)`. Phase 1 = reading files,
 phase 2 = indexing coverage.
 */
typedef void (*PlatypusProgressFn)(void*, uint32_t, uint32_t, uint32_t);

/*
 A C cancel poll: returns nonzero to abort the transfer.
 */
typedef uint8_t (*PlatypusCancelFn)(void*);

/*
 A channel to program, laid out for the C ABI (avoids JSON parsing in the no-serde FFI).
 `mode`: 0=FM 1=NFM 2=AM. `tone_mode`: index into TMODES
 `["","Tone","TSQL","TSQL-R","DTCS","DTCS->","Tone->DTCS","DTCS->Tone"]`; `tone_value` = CTCSS
 Hz×10 (modes 1–3) or the DCS code (modes 4–7). `duplex`: index into
 `["","","-","+","split","off"]` (0=simplex, 2=−, 3=+, 4=split). `offset_hz`: repeater-shift
 magnitude; `tx_hz`: TX frequency for split. `power`: 0=High 1=Mid 2=Low. `step`: index into
 STEPS. `skip`: 0=`""` 1=`S` 2=`P`. `banks`: bit *b* set → member of bank *b*. `name`: up to
 6 chars, NUL-padded.
 */
typedef struct {
    uint16_t slot;
    uint64_t rx_hz;
    uint32_t offset_hz;
    uint32_t tx_hz;
    uint8_t mode;
    uint8_t tone_mode;
    uint16_t tone_value;
    /*
     Second squelch value for the cross tone modes (`Tone->DTCS`/`DTCS->Tone`): the DCS code,
     while `tone_value` holds the CTCSS Hz×10. Ignored for single-value tone modes.
     */
    uint16_t tone_value2;
    uint8_t duplex;
    uint8_t power;
    uint8_t step;
    uint8_t skip;
    uint16_t banks;
    char name[8];
} PlatypusFt60Channel;

/*
 One PMS band-edge record for [`platypus_ft60_apply_pms`]. `index` is the 0-based record
 (interleaved: `2p` = lower / `2p+1` = upper of pair `p`); `used` 0 clears the edge (frequency
 ignored). `freq_hz` is the edge frequency; `step` the tuning-step index.
 */
typedef struct {
    uint16_t index;
    uint8_t used;
    uint64_t freq_hz;
    uint8_t step;
} PlatypusFt60PmsEdge;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Every radio Platypus supports, from the profile registry — the single source of truth
 the app's radio list derives from. JSON array of
 `[{ id, name, maker, transport, class:"sdCard"|"cloneImage" }]`.
 */
char *platypus_radios_json(void);

/*
 The FT-60 channel-form option sets, from the clone-image profile's `field_options` — the
 single source of truth for the editor's pickers. JSON object
 `{ modes, toneModes, steps, powers, duplexes }`, each an array of
 `{ label, code[, valueKind:"none"|"ctcss"|"dcs"] }` (`valueKind` on tone modes only). The
 UI shows `label`, stores/sends `code` — no attribute table lives in the app. Null if no
 clone-image radio is registered.
 */
char *platypus_ft60_options_json(void);

/*
 The RadioReference service-type codes → names, from `core::model::SERVICE_TYPES` — the
 single source the app's `ServiceType` presentation table merges names from (it keeps only
 the SF Symbol + color). JSON array of `[{ code, name }]`.
 */
char *platypus_service_types_json(void);

/*
 The card's current display customization as JSON:
 `{ "globals":[{key,label,value,options:[str]}],
    "items":[{dispOptId,dispLayoutId,tokens:[str]}],
    "colors":[{dispColorId,colorLayoutId,pairs:[{text,back}]}] }`.
 Null if no supported card / no `profile.cfg` is found there.

 # Safety
 `card_mount` must be a valid NUL-terminated C string.
 */
char *platypus_display_config_json(const char *card_mount);

/*
 Apply an edit script to the card's `profile.cfg` and commit (write + fsync + delete
 `app_data.cfg`). The caller must still **eject**. Returns null on success, or an error string.

 `edits` is one edit per line (`\n`), tab-separated:
 - `G<TAB>key<TAB>value` — a global (DisplayOption/Backlight) setting
 - `I<TAB>dispOptId<TAB>dispLayoutId<TAB>index<TAB>token` — an item assignment
 - `C<TAB>dispColorId<TAB>colorLayoutId<TAB>index<TAB>text<TAB>back` — a color pair

 Unknown/blank lines are ignored; the setters are change-gated, so applying an unchanged script
 re-encodes the file byte-for-byte (only untouched-record preservation, never a rewrite of what
 we don't own).

 # Safety
 `card_mount`/`edits` must be valid NUL-terminated C strings.
 */
char *platypus_display_apply(const char *card_mount, const char *edits);

/*
 The allowed color palette: `[{name,hex}]` (147 colors, the display spec's `Color` sheet).
 */
char *platypus_display_palette_json(void);

/*
 The item vocabularies per screen area: `[{dispOptId,label,tokens:[str]}]`.
 */
char *platypus_display_items_json(void);

/*
 The seven display modes: `[{name,dispLayoutId,colorLayoutId}]`.
 */
char *platypus_display_modes_json(void);

/*
 The color-element groups: `[{dispColorId,elements:[str]}]` (nominal element names per group).
 */
char *platypus_display_color_groups_json(void);

/*
 Parse an HPDB `.hpd`/`.cfg` file at `path`. Returns null on any failure.

 # Safety
 `path` must be a valid NUL-terminated C string.
 */
PlatypusHpdb *platypus_open_hpdb(const char *path);

/*
 Free a handle from [`platypus_open_hpdb`]. Safe to call with null.

 # Safety
 `handle` must be a pointer previously returned by `platypus_open_hpdb`, or null.
 */
void platypus_close_hpdb(PlatypusHpdb *handle);

/*
 Free a string returned by any `*_json` function. Safe to call with null.

 # Safety
 `s` must be a pointer previously returned by this library, or null.
 */
void platypus_string_free(char *s);

/*
 JSON array of every system in the document. Null on null handle.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_systems_json(const PlatypusHpdb *handle);

/*
 JSON array of systems tagged with `county_id`.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_systems_in_county_json(const PlatypusHpdb *handle, uint64_t county_id);

/*
 JSON array of systems with a location within `miles` of (`lat`, `lon`).

 # Safety
 `handle` must be valid or null.
 */
char *platypus_systems_in_radius_json(const PlatypusHpdb *handle,
                                      double lat,
                                      double lon,
                                      double miles);

/*
 JSON catalog for the browse/filter/select UI: every system with its
 channel-level detail (the 1B catalog needs service type, tech, encryption,
 TGID/frequency — richer than `platypus_systems_json`). Null on null handle.

 Shape: `[{ "id","name","kind","tech","counties":[u64],"siteCount":u64,
   "channels":[{ "id","name","kind":"Talkgroup"|"Frequency","tgid":str|null,
   "freqHz":u64|null,"mode":str|null,"serviceType":u16|null,"tone":str|null }] }]`
   // `tone` = raw audio option (TONE=/NAC=/ColorCode=…)

 IDs are stable within a load (`s<i>` per system, `s<i>c<j>` per channel) so the
 UI can track a channel-level selection cart.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_catalog_json(const PlatypusHpdb *handle);

/*
 Load every `s_*.hpd` under `dir` into one in-memory library (the full-USA load).
 Null on a bad path or if the directory can't be read. Free with
 [`platypus_library_close`].

 `progress`, if non-null, is invoked as `progress(ctx, phase, done, total)` during
 the load — **phase 1** = reading files, **phase 2** = indexing coverage — so the UI
 can show a real percentage off the main thread instead of a frozen window.

 # Safety
 `dir` must be a valid NUL-terminated C string. `progress` (if set) must be a valid
 function pointer and `ctx` must outlive the call.
 */
PlatypusLibrary *platypus_library_open(const char *dir, void *ctx, PlatypusProgressFn progress);

/*
 Free a library handle. Safe with null.

 # Safety
 `handle` must come from [`platypus_library_open`], or be null.
 */
void platypus_library_close(PlatypusLibrary *handle);

/*
 JSON `{files, systems, channels}` for a load summary.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_library_stats_json(const PlatypusLibrary *handle);

/*
 Filtered catalog: **system-level** rows matching the filter (no channels — the
 UI lazy-loads those per system via [`platypus_library_channels_json`]). Each
 row: `{id,name,kind,tech,counties,siteCount,channelCount}` where `channelCount`
 is the number of channels passing the current filter. A system appears only if
 it passes the tech filter and has ≥1 matching channel.

 Filter params (all optional — empty string / false = no constraint):
 - `services_csv`: service-type codes, e.g. `"3,8"` (channel-level).
 - `techs_csv`: tech categories, e.g. `"P25,DMR,Analog"` (system-level, fuzzy).
 - `search`: case-insensitive match on system name or channel name.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_library_catalog_json(const PlatypusLibrary *handle,
                                    const char *services_csv,
                                    const char *techs_csv,
                                    const char *search);

/*
 Channels of one system (by `id` = `"d<di>s<si>"` from a catalog row), filtered
 the same way as the catalog. This is the lazy-load on expand. Empty array on a
 bad id.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_library_channels_json(const PlatypusLibrary *handle,
                                     const char *system_id,
                                     const char *services_csv,
                                     const char *search);

/*
 County-scoped channels of one system: only the channels whose group is placed in
 `county` (location-first). Use this when the system was opened from inside a
 county, so a statewide system (e.g. SAFE-T) shows just that county's talkgroups.
 `county == 0` returns the **no-county** bucket (the state-level statewide-residual
 channels). Channel ids keep their system-wide index so the cart/writer are
 unaffected. Empty array on a bad id / unknown placement.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_library_county_channels_json(const PlatypusLibrary *handle,
                                            const char *system_id,
                                            uint64_t county,
                                            const char *services_csv,
                                            const char *search);

/*
 **Radius-scoped** channels of one system: only the voice channels whose parent
 department (`C-Group`/`T-Group`) has its geo center within `miles` of
 (`lat`, `lon`). The location-first "add only what's near here" for the map view —
 e.g. add a statewide P25 system from a point and get just that area's talkgroups,
 not every county's. Channel ids match `platypus_library_channels_json`
 (`d<i>s<j>c<k>`), so the result feeds straight into the append/build path. Groups
 with no geo (0,0) are excluded (not location-specific). Empty array on a bad id.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_library_radius_channels_json(const PlatypusLibrary *handle,
                                            const char *system_id,
                                            double lat,
                                            double lon,
                                            double miles,
                                            const char *services_csv,
                                            const char *search);

/*
 Geo-located systems within `miles` of (`lat`, `lon`) for the **map** view. Each
 system that has a geo-bearing record (site/group) in range and ≥1 filter-passing
 channel is returned with the in-range point nearest the center as its pin, the
 point's coverage `rangeMi`, and the system's dominant service-type code (for the
 pin color). Reuses the catalog filter params. Tap a pin → fetch its channels by
 `id` (`platypus_library_channels_json`).

 Shape: `[{ "id":"d<i>s<j>","name","kind","tech":str|null,"serviceType":u16|null,
   "lat":f64,"lon":f64,"rangeMi":f64 }]`

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_library_geo_json(const PlatypusLibrary *handle,
                                double lat,
                                double lon,
                                double miles,
                                const char *services_csv,
                                const char *techs_csv,
                                const char *search);

/*
 If `volume_root` is a mounted scanner card — it has a recognized model folder whose
 HPDB directory holds state files (`s_*.hpd`) — return that HPDB directory's absolute
 path (caller frees with [`platypus_string_free`]); null otherwise. Lets the app
 auto-discover a connected card under `/Volumes` instead of making the user navigate.

 # Safety
 `volume_root` must be a valid NUL-terminated C string.
 */
char *platypus_card_hpdb_dir(const char *volume_root);

/*
 The favorites lists currently on a mounted card, plus the detected scanner model
 and its limits — for seeing/managing the existing configuration. `card_mount` is
 the volume root (the parent of the model folder). Null if no supported card is
 found there.

 Shape: `{ "model":str, "modelId":str|null, "maxFavorites":u32,
   "lists":[{ "slot":u32,"name":str,"filename":str,"systems":u64,
              "channels":u64,"bytes":u64,"monitor":bool,
              "quickKey":u32|null,"numberTag":u32|null }] }`
 (`maxFavorites` 0 = unknown; `monitor`/`quickKey`/`numberTag` = F-List settings;
 null quick key / number tag = "Off").

 # Safety
 `card_mount` must be a valid NUL-terminated C string.
 */
char *platypus_card_favorites_json(const char *card_mount);

/*
 Sort the card's favorites lists **alphabetically by name** (the order shown on the
 scanner). Returns null on success, or an error string. Caller must still eject.

 # Safety
 `card_mount` must be a valid NUL-terminated C string.
 */
char *platypus_card_sort_lists(const char *card_mount);

/*
 Reorder the card's favorites lists into an explicit slot order (`slots_csv`, e.g.
 `"3,1,2"`); slots not listed keep their order at the end. For manual (drag/up-down)
 reordering. Returns null on success, or an error string. Caller must still eject.

 # Safety
 `card_mount`/`slots_csv` must be valid NUL-terminated C strings.
 */
char *platypus_card_reorder_lists(const char *card_mount, const char *slots_csv);

/*
 Sort the systems of a favorites list **alphabetically**, returning a **new**
 handle. Save with [`platypus_favorites_commit`]. Null on a null handle.

 # Safety
 `handle` must be valid or null.
 */
PlatypusFavorites *platypus_favorites_sort(const PlatypusFavorites *handle);

/*
 Delete a favorites list (slot file + `f_list.cfg` entry + `app_data.cfg`) from a
 mounted card. Returns **null on success**, or an error message (free it) on
 failure. The caller must still **eject** the volume afterward.

 # Safety
 `card_mount` must be a valid NUL-terminated C string.
 */
char *platypus_card_delete_slot(const char *card_mount, uint32_t slot);

/*
 JSON array of states from an `hpdb.cfg` — `[{id,name,abbr,country}]`, the top of
 the Country → State → County hierarchy. Parses `StateInfo` lines directly.
 Stateless (no handle). Null on failure.

 # Safety
 `path` must be a valid NUL-terminated C string.
 */
char *platypus_states_json(const char *path);

/*
 JSON array of counties from an `hpdb.cfg` at `path` — `[{id,name,state}]`.
 Stateless (no handle). Null on failure.

 # Safety
 `path` must be a valid NUL-terminated C string.
 */
char *platypus_counties_json(const char *path);

/*
 Build a favorites document from a source HPDB by selection + options. The whole
 pipeline we validated on hardware, callable from any UI:
 - `selector`: `"all"`, `"county:712"`, `"tech:P25"`, or `"name:SAFE-T"`.
 - `near_miles > 0`: also prune sites + talkgroup groups to within that many miles
   of (`near_lat`, `near_lon`) — the location-first filter. `<= 0` skips it.
 - `departments_on`: the DQKs quick-key preference (both values work).
 - `band_plan`: add a band plan to kept P25 sites (rare; needed by some simulcasts).

 Returns an opaque handle (free with [`platypus_favorites_free`]), or null on a
 bad selection / null source.

 # Safety
 `src` must be valid or null; `selector` a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_build(const PlatypusHpdb *src,
                                            const char *selector,
                                            double near_lat,
                                            double near_lon,
                                            double near_miles,
                                            bool departments_on,
                                            bool band_plan);

/*
 Build favorites from an explicit set of channel ids (the selection cart) over a
 loaded [`PlatypusLibrary`]. `channel_ids_csv` is a comma-separated list of catalog
 ids (`"d<di>s<si>c<ci>"`). Channels are grouped by source file + system, subset
 (keeping only the chosen voice channels plus the scaffolding needed to tune them:
 header, sites, control freqs, parent groups), merged under one preamble, then run
 through the validated favorites build. Returns a handle (preview/commit via the
 other favorites functions), or null on bad input / empty selection.

 # Safety
 `lib` valid or null; `channel_ids_csv` a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_from_channels(const PlatypusLibrary *lib,
                                                    const char *channel_ids_csv,
                                                    bool departments_on,
                                                    bool band_plan);

/*
 A new, empty favorites list (just the model header) — for building a list from
 scratch (the "+ New list" flow). Grow it with
 [`platypus_favorites_append_from_library`], then name + commit. Null if no scanner
 model is registered.

 # Safety
 Takes no arguments; free the returned handle with [`platypus_favorites_free`].
 */
PlatypusFavorites *platypus_favorites_new(void);

/*
 Open an existing favorites list from a card slot as an editable handle (parse the
 `f_<slot>.hpd` file). Null if the card/model/slot can't be read. Free with
 [`platypus_favorites_free`]; inspect via [`platypus_favorites_channels_json`].

 # Safety
 `card_mount` must be a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_open(const char *card_mount, uint32_t slot);

/*
 The systems + channels in a favorites list (same shape as `platypus_catalog_json`:
 channel ids are `"s<si>c<ci>"`), for the edit UI.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_favorites_channels_json(const PlatypusFavorites *handle);

/*
 A favorites list as a **scan/avoid tree**: systems → departments (groups) →
 channels, each carrying its `avoid` flag, so the UI can show and toggle what the
 radio actually scans. Channel ids match `platypus_favorites_channels_json`
 (`"s<si>c<ci>"`, system-wide voice index); group ids are `"s<si>g<gi>"`.

 Shape: `[{ "id","name","kind","tech":str|null,"avoid":bool,
   "groups":[{ "id","name","avoid":bool,
     "channels":[{ "id","name","tgid":str|null,"freqHz":u64|null,"mode":str|null,
       "serviceType":u16|null,"tone":str|null,"avoid":bool,"priority":bool,
       "settings":{ <field>:str … } }] }] }]`  // `tone` = raw audio option; settings = editable fields

 # Safety
 `handle` must be valid or null.
 */
char *platypus_favorites_tree_json(const PlatypusFavorites *handle);

/*
 Set the **Avoid** flag on one record (scan ⇄ skip), returning a **new** handle.
 `target` is `"s<si>"` (system), `"s<si>g<gi>"` (department), or `"s<si>c<ci>"`
 (channel). Null on a null handle / unparseable target.

 # Safety
 `handle` valid or null; `target` a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_set_avoid(const PlatypusFavorites *handle,
                                                const char *target,
                                                bool avoid);

/*
 Set a channel's **Priority Channel** flag, returning a **new** handle. `target`
 is a channel id `"s<si>c<ci>"` (system/department targets are ignored — priority
 is per-channel). Null on a null handle / unparseable target.

 # Safety
 `handle` valid or null; `target` a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_set_priority(const PlatypusFavorites *handle,
                                                   const char *target,
                                                   bool on);

/*
 Set an editable per-channel **value** field (e.g. `field` = "delay") on a channel,
 returning a **new** handle. `target` is a channel id `"s<si>c<ci>"`; `value` is the
 raw field value. Null on a null handle / unparseable (non-channel) target.

 # Safety
 `handle` valid or null; `target`/`field`/`value` valid NUL-terminated C strings.
 */
PlatypusFavorites *platypus_favorites_set_channel_value(const PlatypusFavorites *handle,
                                                        const char *target,
                                                        const char *field,
                                                        const char *value);

/*
 Remove channels (by `"s<si>c<ci>"` id) from a favorites list, returning a **new**
 handle. Systems left with no channels are dropped. Null on bad input.

 # Safety
 `handle` valid or null; `channel_ids_csv` a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_remove(const PlatypusFavorites *handle,
                                             const char *channel_ids_csv);

/*
 Append library channels (`"d<di>s<si>c<ci>"`) to a favorites list, returning a
 **new** handle (for "add to an existing list"). The added systems are built into
 the favorites dialect and concatenated after the existing ones (no dedupe yet).
 Null on bad input.

 # Safety
 `fav`/`lib` valid or null; `channel_ids_csv` a valid NUL-terminated C string.
 */
PlatypusFavorites *platypus_favorites_append_from_library(const PlatypusFavorites *fav,
                                                          const PlatypusLibrary *lib,
                                                          const char *channel_ids_csv,
                                                          bool departments_on);

/*
 Free a favorites handle. Safe with null.

 # Safety
 `handle` must come from [`platypus_favorites_build`], or be null.
 */
void platypus_favorites_free(PlatypusFavorites *handle);

/*
 JSON summary for a write preview: `{systems, sites, dqks, bandPlans, bytes}`.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_favorites_summary_json(const PlatypusFavorites *handle);

/*
 The systems in a built favorites list (same shape as `platypus_systems_json`),
 for the preview UI.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_favorites_systems_json(const PlatypusFavorites *handle);

/*
 Commit a built favorites list to a mounted card: write `f_<slot>.hpd`, register
 it in `f_list.cfg`, delete `app_data.cfg`, all `fsync`'d. Returns **null on
 success**, or an error message (free with [`platypus_string_free`]) on failure.
 The caller must still **eject** the volume afterward (platform-specific).

 # Safety
 `handle` must be valid or null; `card_mount`/`label` valid NUL-terminated strings.
 */
char *platypus_favorites_commit(const PlatypusFavorites *handle,
                                const char *card_mount,
                                uint32_t slot,
                                const char *label);

/*
 Write **only** this favorites list's slot file `f_<slot>.hpd` (fsync'd) — no
 `f_list.cfg` / `app_data.cfg` change. The content half of the batched save:
 write each changed list's slot, then one [`platypus_card_apply_layout`] pass.
 Returns **null on success**, else an error (free it). Caller must **eject**.

 # Safety
 `handle` valid or null; `card_mount` a valid NUL-terminated string.
 */
char *platypus_favorites_write_slot(const PlatypusFavorites *handle,
                                    const char *card_mount,
                                    uint32_t slot);

/*
 Apply the full favorites layout in one structural pass: `entries` is the complete
 ordered list of `slot \t name [\t monitor \t quickkey \t numbertag]` lines
 separated by `\n` (TAB and LF can't occur in a card list name). The optional
 trailing fields set that list's **Monitor** (`On`/`Off`), **Quick key**
 (`Off`/`0`-`99`), and **NumberTag** (`Off`/`0`-`99`); an empty/absent field leaves
 it unchanged. Those become the entire `f_list.cfg`; any previously-registered slot
 not present is deleted; `app_data.cfg` is deleted. Every surviving list's other
 F-List fields are preserved verbatim. Returns **null on success**, else an error
 (free it). Caller must **eject**.

 # Safety
 `card_mount`/`entries` valid NUL-terminated strings.
 */
char *platypus_card_apply_layout(const char *card_mount, const char *entries);

/*
 Candidate serial ports as a JSON array of device paths (`/dev/cu.*`).
 */
char *platypus_serial_ports_json(void);

/*
 Read + decode an FT-60 clone image over serial `port`. Returns a handle, or null on
 failure/cancel (with `*err_out` set to a heap message the caller frees). Non-destructive
 — only the `0x06` clone-handshake ACK is written, never radio memory.

 # Safety
 `port` must be a valid C string; `err_out` a valid pointer or null; the callbacks + `ctx`
 must remain valid for the duration of the call.
 */
PlatypusFt60 *platypus_ft60_read(const char *port,
                                 void *ctx,
                                 PlatypusProgressFn progress,
                                 PlatypusCancelFn cancel,
                                 char **err_out);

/*
 Save a read handle's raw clone image as a `.img` **backup** — the restore point captured on
 every radio Read. Writes `<dir>/<stem>.img`, creating `dir` and `fsync`ing the file so the
 bytes are durably on disk (the same "an `Ok` isn't enough until it's flushed" discipline as the
 card path). The persistence lives here in the core FFI, not the app, so every front-end backs
 up identically. Returns the backup file path (caller frees with [`platypus_string_free`]), or
 null + `*err_out` on failure.

 # Safety
 `handle` valid or null; `dir`/`stem` valid C strings; `err_out` valid or null.
 */
char *platypus_ft60_backup(const PlatypusFt60 *handle,
                           const char *dir,
                           const char *stem,
                           char **err_out);

/*
 The decoded standard memories as a JSON array — the shape the FT-60 editor consumes.
 Every enumerated field crosses as its on-radio **code** (symmetric with the write struct
 `PlatypusFt60Channel`), so the app never string-matches an attribute: `[{ slot, name,
 freqHz, modeCode, toneModeCode, toneMode:"off"|"ctcss"|"dcs"|"cross", toneValue, toneValue2,
 duplexCode, offsetHz, txHz, power, step, skip:0|1|2, banks:[u8] }]`. The codes index the
 option lists from [`platypus_ft60_options_json`]. `toneMode` is the value-kind for
 reconstructing the squelch value; for `"cross"` (`Tone->DTCS`/`DTCS->Tone`) `toneValue` is the
 CTCSS Hz×10 and `toneValue2` the DCS code. `skip` 0=none/1=S/2=P.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_ft60_memories_json(const PlatypusFt60 *handle);

/*
 Free an FT-60 image handle.

 # Safety
 `handle` must be from [`platypus_ft60_read`] or null, and unused afterward.
 */
void platypus_ft60_free(PlatypusFt60 *handle);

/*
 Borrow the raw image bytes of a read handle (valid until the handle is freed). Sets
 `*out_len` and returns a pointer; the caller should copy them out before freeing. Null +
 `*out_len = 0` on a null handle.

 # Safety
 `handle` must be valid or null; `out_len` a valid pointer.
 */
const uint8_t *platypus_ft60_image_bytes(const PlatypusFt60 *handle, size_t *out_len);

/*
 Write (clone-out) `bytes` to the FT-60 over serial `port`. The radio must be in CLONE
 **receive** (`-WAIT-`). Returns 1 on success, 0 on failure/cancel with `*err_out` set to a
 heap message (free with [`platypus_string_free`]). **WARNING: this writes radio memory** —
 pass only an image that round-trips (the bytes from a read, or an edit past the gate).

 # Safety
 `port` a valid C string; `bytes` valid for `len`; `err_out` valid or null; the callbacks +
 `ctx` must outlive the call.
 */
uint8_t platypus_ft60_write(const char *port,
                            const uint8_t *bytes,
                            size_t len,
                            void *ctx,
                            PlatypusProgressFn progress,
                            PlatypusCancelFn cancel,
                            char **err_out);

/*
 Apply an edited channel set onto `base` and return a new handle carrying the edits + a valid
 checksum (a pure transform — no I/O). Read the result with [`platypus_ft60_image_bytes`],
 then clone it out with [`platypus_ft60_write`]. Re-applying the channels a read produced is a
 byte-for-byte no-op (the round-trip gate). Null on a bad base image (`*err_out` set).

 # Safety
 `base` must be valid for `base_len`; `chans` valid for `chans_len` (or null when 0);
 `err_out` a valid pointer or null.
 */
PlatypusFt60 *platypus_ft60_apply(const uint8_t *base,
                                  size_t base_len,
                                  const PlatypusFt60Channel *chans,
                                  size_t chans_len,
                                  char **err_out);

/*
 Apply edited PMS band-edge records onto `base` and return a new handle carrying the edits + a
 valid checksum (a pure transform — no I/O), parallel to [`platypus_ft60_apply`]. Only the
 records you pass are touched (partial-apply); read the result with
 [`platypus_ft60_image_bytes`] and clone it out with [`platypus_ft60_write`]. Re-applying the
 edges a read produced is a byte-for-byte no-op (the round-trip gate). Null on a bad base image
 (`*err_out` set).

 # Safety
 `base` must be valid for `base_len`; `edges` valid for `edges_len` (or null when 0);
 `err_out` a valid pointer or null.
 */
PlatypusFt60 *platypus_ft60_apply_pms(const uint8_t *base,
                                      size_t base_len,
                                      const PlatypusFt60PmsEdge *edges,
                                      size_t edges_len,
                                      char **err_out);

/*
 The programmed PMS band-edge memories as a JSON array — the shape the FT-60 editor's scan-edge
 section consumes: `[{ index, freqHz, step }]` (only `used` edges; index 0..100, interleaved
 lower/upper pairs). Empty `[]` when none are set.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_ft60_pms_json(const PlatypusFt60 *handle);

/*
 The FT-60 set-mode settings as a JSON array (spec order) — the shape the settings editor
 consumes: `[{ key, label, value, options:[str] }]`. `value` indexes `options`. Null on a null
 handle.

 # Safety
 `handle` must be valid or null.
 */
char *platypus_ft60_settings_json(const PlatypusFt60 *handle);

/*
 Apply edited set-mode settings onto `base` (values in `settings_specs` order) and return a new
 handle carrying the edits + a valid checksum — parallel to [`platypus_ft60_apply`]. Read the
 result with [`platypus_ft60_image_bytes`] and clone it out with [`platypus_ft60_write`].
 Change-gated, so re-applying a read's settings is a byte-for-byte no-op. Null on a bad base
 image (`*err_out` set).

 # Safety
 `base` valid for `base_len`; `values` valid for `values_len` (or null when 0); `err_out` valid
 or null.
 */
PlatypusFt60 *platypus_ft60_apply_settings(const uint8_t *base,
                                           size_t base_len,
                                           const uint8_t *values,
                                           size_t values_len,
                                           char **err_out);

/*
 Validate credentials against RR (`getUserData`) — the "Add source" pre-flight. Returns
 `{"username","subExpireDate"}` JSON on success, or sets `*err_out` to the RR message (e.g. a bad
 login fault) and returns null. Bypasses the on-disk cache (the account response is per-user, and
 the cache key is deliberately credential-free), so this always makes a live check.

 # Safety
 The C-string params must be valid NUL-terminated or null; `err_out` valid or null.
 */
char *platypus_rr_validate(const char *app_key,
                           const char *username,
                           const char *password,
                           char **err_out);

/*
 Open a browse session for a location. `selector` is `"zip:<zipcode>"` for now (structured so
 `county:`/`state:`/`metro:`/`prox:` can join later). Runs the cheap two-call location→system-list
 fetch; per-system channels load lazily via [`platypus_rr_source_channels_json`]. `progress`
 reports `(ctx, phase, done, total)` (phase 1 = resolving location, 2 = fetching the county list);
 `cancel` returning nonzero aborts. On failure sets `*err_out` and returns null.

 # Safety
 C-string params valid NUL-terminated or null; `err_out` valid or null; `ctx` is passed back to
 the callbacks untouched.
 */
PlatypusRrSource *platypus_rr_source_open(const char *app_key,
                                          const char *username,
                                          const char *password,
                                          const char *selector,
                                          void *ctx,
                                          PlatypusProgressFn progress,
                                          PlatypusCancelFn cancel,
                                          char **err_out);

/*
 The county's systems as catalog rows (same shape as `platypus_library_catalog_json`). Names come
 from the one `getCountyInfo` call; `tech`/counts fill in once a system is drilled (cached).
 Only the `search` (name) filter applies here — service/tech filters need channel data, so they
 apply in the channel view. Empty array on a null handle.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_rr_source_systems_json(const PlatypusRrSource *handle,
                                      const char *_services_csv,
                                      const char *_techs_csv,
                                      const char *search);

/*
 Channels of one system (`system_ref` = a row `id`), fetched lazily on first call and cached.
 Same shape as `platypus_library_channels_json`. Applies the service-type + `search` filters.
 Empty array on a null handle / bad ref; sets nothing on a fetch error (returns what mapped).

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_rr_source_channels_json(PlatypusRrSource *handle,
                                       const char *system_ref,
                                       const char *services_csv,
                                       const char *search);

/*
 A trunked system's talkgroup **categories**, ranked nearest-first for a location-first drill.
 `all == 0` returns only in-range + systemwide categories (the local view); `all != 0` includes
 the out-of-area ones ("show all areas"). Shape:
 `[{ "id":tgCid,"name","distanceMi":f64|null,"local":bool,"systemwide":bool }]`. Empty array for a
 non-trunked ref or a null handle.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_rr_source_categories_json(PlatypusRrSource *handle,
                                         const char *system_ref,
                                         uint8_t all);

/*
 A talkgroup category's channels — `getTrsTalkgroups(sid, tgCid)` mapped to channels, fetched
 lazily and cached. Same shape as [`platypus_rr_source_channels_json`]. Empty array for a
 non-trunked ref / null handle.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_rr_source_category_channels_json(PlatypusRrSource *handle,
                                                const char *system_ref,
                                                uint32_t tg_cid,
                                                const char *services_csv,
                                                const char *search);

/*
 The county's systems as map pins (same shape as `platypus_library_geo_json`). A drilled system
 uses its nearest site/subcat location; an un-drilled one falls back to the county centroid, so
 the map is populated immediately and refines as systems are opened. `lat`/`lon`/`miles` are
 accepted for signature parity with the library but not used to prune (the set is already the one
 county). Empty array on a null handle.

 # Safety
 `handle` valid or null; the C-string params valid NUL-terminated or null.
 */
char *platypus_rr_source_geo_json(PlatypusRrSource *handle,
                                  double _lat,
                                  double _lon,
                                  double _miles,
                                  const char *_services_csv,
                                  const char *_techs_csv,
                                  const char *search);

/*
 The resolved location + system count for the browse header (the location chip).
 Shape: `{ "city","ctid":u64,"stid":u64,"lat":f64,"lon":f64,"systemCount":u64 }`. Null on a null
 handle.

 # Safety
 `handle` valid or null.
 */
char *platypus_rr_source_location_json(const PlatypusRrSource *handle);

/*
 Warm trunked systems' real map sites, returning how many were warmed (0 when all are done). Every
 **already-cached** site is warmed at once (disk hits — instant, so a switch back to a visited county
 loads immediately); only **live** fetches are paced — at most `batch`, in parallel on forked clients
 (so the per-client throttle doesn't serialize them). The app calls this in a loop, reloading the map
 after each call, so first-visit pins refine in bursts without blocking.

 # Safety
 `handle` valid or null.
 */
uint32_t platypus_rr_source_warm_batch(PlatypusRrSource *handle,
                                       uint32_t batch);

/*
 Manual "Refresh": force-refetch the location's base data live (bypassing the cache), so a
 stale-cached county/site set updates on demand. Clears the in-memory memos (drilled talkgroups
 then refresh per TTL/upstream on next open), re-fetches `getCountyInfo` + the map site geo under
 the force flag, then clears it. Returns the fresh location JSON (with the new `fetchedAt`), or
 null on a null handle.

 # Safety
 `handle` valid or null.
 */
char *platypus_rr_source_refresh(PlatypusRrSource *handle);

/*
 Free a source handle (safe with null).

 # Safety
 `handle` must be a pointer from [`platypus_rr_source_open`] not already freed, or null.
 */
void platypus_rr_source_free(PlatypusRrSource *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLATYPUS_H */
